#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".



if command -v shellcheck &>/dev/null; then

	files=$(git diff --cached --name-only)
	for file in $files; do
	if [ "text/x-shellscript" == "$(file -b --mime-type "${file}")" ];then
		if  ! shellcheck "${file}" &>/dev/null ; then
			echo "${file} does not meet shellchecks standards"
			exit 1
			fi
	fi
	done

else 
  echo "You must install shellcheck to contribute to this repository"
  exit 1
fi
 



