sudo: required

services:
  - docker

before_install:
  - echo "repo_token\:${COVERALLS_TOKEN}" > .coveralls.yml
  - docker build -t bats .

script:
  - docker run  -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" bats