sudo: required

services:
  - docker

before_install:
  - echo "repo_token\:${COVERALLS_TOKEN}" > .coveralls.yml
  - docker build -t bats .

script:
  - docker run bats
  - docker run -e LOC=/root/run.json bats
  - docker run -e LOC=/etc/run/run.json bats
  - docker run -e BACK_LOC=/root/run.json bats "./multi_file.bats"
  - docker run -e BACK_LOC=/etc/run/run.json -e LOC=/root/run.json bats "./multi_file.bats"
  - docker run bats "./home.bats"